### ISSUE TITLE
Only partial parsing of documents

### ISSUE THREAD

**Issue by NorfairKing** [digitalmentat/orgmode-parse#12] opened 2015-07-14 20:49 UTC
Any use of `parseDocument` will result in a partial parsing.

To reproduce:
Apply `parse (parseDocument [])` to this text file:
```
* Heading
```
Giving a empty `""` string to the resulting partial's parser results in the document as expected:

```

parseDoc :: Text -> Document
parseDoc text = case parse (parseDocument []) text of
                  Partial f -> case f "" of
                                Done _ doc -> doc
```

**Comment by NorfairKing** [comment] 2015-07-20 08:42
Has this been accepted as a bug?

**Comment by ixmatus** [comment] 2015-07-20 13:27
Yes it has. I didn't have a chance to work on it though over the weekend.

**Comment by NorfairKing** [comment] 2015-07-25 16:59
Any progress?

**Comment by ixmatus** [comment] 2015-07-26 00:46
Nope, too busy w/ RL at the moment, I'm planning on tackling this and a few
other things soon though.
ᐧ

On Sat, Jul 25, 2015 at 11:59 AM, Tom Sydney Kerckhove <
notifications@github.com> wrote:

> Any progress?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalmentat/orgmode-parse/issues/12#issuecomment-124862145>
> .
>



-- 
Parnell Springmeyer
parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
<http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>

**Comment by ixmatus** [comment] 2015-08-03 01:26
I'm closing this because after much further investigation, this is not a bug, it is expected behavior.

If you use the `parse` function it will certainly return a Partial result because we use the `many` combinators in order to perform 0 or more matches of a heading, sub-headings, sections, &c... When using 0 or more many combinators the parse doesn't know if it has reached the end or not and it therefore terminates with a Partial, asking for either another one or nothing (feeding it an empty string).

This is by design and very common when using Attoparsec. You may either using `parseOnly` which will complete or fail without a partial, or simply feed it an empty string to tell the parser that you're done.

**Closed by ixmatus** 2015-08-03 01:26 UTC
